apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-static
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  addresses:
    - 192.168.178.201-192.168.178.229
  autoAssign: false

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-dynamic
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  addresses:
    - 192.168.178.230-192.168.178.250
  autoAssign: true

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-all
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  ipAddressPools:
    - lb-static
    - lb-dynamic
