{{- if .Values.argoCd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/hal-47/halkube.git
    targetRevision: {{ .Values.argoCd.revision | default "HEAD" | quote }}
    path: charts/argo-cd
    helm:
      releaseName: argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.argoCd.namespace | default "argocd" | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}