{{- if .Values.metallb.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: {{ .Values.metallb.chartVersion | default "*" | quote }}
    helm:
      releaseName: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.metallb.namespace | default "metallb-system" | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}