{{- if (index .Values "metallb" "enabled") }}
{{- /* Argo CD Namespace robust ermitteln (argocd oder argoCd, Fallback "argocd") */ -}}
{{- $argocdNs := default "argocd" (or .Values.argocd.namespace .Values.argoCd.namespace) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: {{ $argocdNs | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.metallb.project | default "platform" | quote }}
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: {{ .Values.metallb.chartVersion | default "0.15.2" | quote }}
      helm:
        releaseName: {{ .Values.metallb.releaseName | default "metallb" | quote }}

    {{- $repoURL := (coalesce (index .Values "metallb" "repoURL") (index .Values "global" "repoURL") "https://github.com/hal-47/halkube.git") }}
    {{- $revision := (coalesce (index .Values "metallb" "revision") "HEAD") }}
    {{- $path := (coalesce (index .Values "metallb" "path") "apps/manifests/metallb") }}
    - repoURL: {{ $repoURL | quote }}
      targetRevision: {{ $revision | quote }}
      path: {{ $path | quote }}
      directory:
        recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.metallb.namespace | default "metallb-system" | quote }}

  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
{{- end }}