{{- if .Values.perlite.enabled }}
{{- $argocdNs := default "argocd" (or .Values.argocd.namespace .Values.argoCd.namespace) -}}
{{- $ns := default "perlite" .Values.perlite.namespace -}}
{{- $repoURL := coalesce .Values.perlite.repoURL .Values.global.repoURL "https://github.com/hal-47/halkube.git" -}}
{{- $revision := default "HEAD" .Values.perlite.revision -}}
{{- $path := default "apps/manifests/perlite" .Values.perlite.path -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perlite
  namespace: {{ $argocdNs | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.perlite.syncWave | default "70" | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.perlite.project | default "platform" | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $ns | quote }}
  source:
    repoURL: {{ $repoURL | quote }}
    targetRevision: {{ $revision | quote }}
    path: {{ $path | quote }}
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}