{{- if .Values.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.traefik.namespace | default "traefik" | quote }}
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: {{ .Values.traefik.chartVersion | default "37.1.1" | quote }}
    helm:
      releaseName: traefik
      values: |
        # --- IngressClass ---
        ingressClass:
          enabled: true
          isDefaultClass: true
          name: traefik

        # --- Provider (CRD + Ingress) ---
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true

        # --- Services/Ports: ClusterIP (f체r Cloudflared) ---
        service:
          enabled: true
          type: ClusterIP

        ports:
          web:
            port: 8000
            expose: true
            exposedPort: 80
          websecure:
            port: 8443
            expose: true
            exposedPort: 443
            tls:
              enabled: true

        # --- HTTPS erzwingen & ACME (DNS-01 via Cloudflare) ---
        additionalArguments:
          - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
          - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
          - "--certificatesresolvers.cloudflare.acme.email={{ .Values.global.acmeEmail | default "admin@h47.eu" }}"
          - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
          - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
          # optional: zus채tzliche Resolver f체r schnellere DNS-Pr체fung
          - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
          # optional vorab Wildcards ziehen (nicht zwingend, Traefik kann on-demand):
          - "--certificatesresolvers.cloudflare.acme.domains[0].main=h47.eu"
          - "--certificatesresolvers.cloudflare.acme.domains[0].sans=*.h47.eu"
          - "--certificatesresolvers.cloudflare.acme.domains[1].main=intern.h47.eu"
          - "--certificatesresolvers.cloudflare.acme.domains[1].sans=*.intern.h47.eu"

        # --- ACME-Speicher persistent ---
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 1Gi
          path: /data

        # --- Cloudflare API Token aus Secret ---
        env:
          - name: CF_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: traefik-cloudflare
                key: token

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}