{{- if .Values.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: {{ .Values.traefik.chartVersion | default "*" | quote }}
    helm:
      releaseName: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.traefik.namespace | default "traefik" | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}