{{- if .Values.traefik.enabled }}
{{- $argocdNs := default "argocd" (or .Values.argocd.namespace .Values.argoCd.namespace) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-extras
  namespace: {{ $argocdNs | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "31"   # nach Traefik (wave 30)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    repoURL: {{ (.Values.repoURL | default .Values.global.repoURL) | required "Set .Values.repoURL or .Values.global.repoURL to your Git URL" | quote }}
    targetRevision: {{ (.Values.targetRevision | default .Values.global.targetRevision | default "HEAD") | quote }}
    path: apps/components/traefik-internal
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}