argo-cd:
  configs:
    cm:
      url: https://192.168.178.85:30443
    params:
      server.insecure: "false"
  server:
    service:
      type: NodePort
      # nur https, klar und eindeutig
      ports:
        - name: https
          port: 443
          nodePort: 30443
          protocol: TCP
          targetPort: 8080