apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: traefik
  annotations:
    metallb.universe.tf/address-pool: lb-static
    metallb.universe.tf/loadBalancerIPs: "192.168.178.222"   # gewünschte IP
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.222  # optional zusätzlich (harmoniert mit MetalLB)
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: websecure
      port: 443
      targetPort: websecure