apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: traefik
  annotations:
    metallb.universe.tf/address-pool: lb-static
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.202  # optional zusätzlich (harmoniert mit MetalLB)
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: websecure
      port: 443
      targetPort: websecure