baseDomain: intern.h47.eu

argocd:
  enabled: true
  revision: HEAD
  namespace: argocd
  host: argocd.intern.h47.eu

metallb:
  enabled: true
  path: "apps/manifests/metallb"
  revision: "HEAD"

longhorn:
  enabled: true
  chartVersion: "1.9.1"
  namespace: longhorn-system
  host: longhorn.intern.h47.eu

traefik:
  enabled: true
  chartVersion: "37.1.1"
  namespace: traefik
  repoURL: "https://github.com/hal-47/halkube.git"
  targetRevision: "main"   # oder dein Branch/Tag

perlite:
  enabled: true
  namespace: perlite
  repoURL: "https://github.com/hal-47/halkube.git"
  revision: HEAD
  path: "apps/manifests/perlite"

global:
  repoURL: "https://github.com/hal-47/halkube.git"
  acmeEmail: "admin@h47.eu"